

# (default) ... build the lab2a executable.


lab2b: lab2c.c SortedList.h SortedList.c
	gcc -pthread lab2c.c SortedList.h SortedList.c -o lab2c


	

dist:
	tar -cvf lab2c-804424176.tar.gz lab2c.c Makefile  README graph1.png  SortedList.h SortedList.c

