lab2a : lab2a.c
	@gcc -lrt -o lab2a lab2a.c
	@chmod +x lab2a



clean:
	@-rm -f lab2a.o
	@-rm -f lab2a



dist:
	tar -cvf lab2a-804424176.tar.gz lab2a.c makefile  README graph1_single_thread.png graph2_different_protection.png
